stages:
  - build
  - push

build-test:
  image: docker:stable
  stage: build
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:19.03.1-dind
  script:
   - docker build -t $CI_REGISTRY_IMAGE:tmp .
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
   - docker push $CI_REGISTRY_IMAGE:tmp
  tags:
    - build
  only:
  - master

push-staging:
  image: docker:stable
  stage: push
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:19.03.1-dind
  script:
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
   - docker image pull $CI_REGISTRY_IMAGE:tmp
   - docker image tag $CI_REGISTRY_IMAGE:tmp $CI_REGISTRY_IMAGE:staging-$CI_BUILD_REF
   - docker push $CI_REGISTRY_IMAGE:staging-$CI_BUILD_REF
  tags:
    - build
  only:
  - master
  
